### ISSUE TITLE
[Missing feature]: Warp dust no recipe

### ISSUE THREAD

**Issue by MalekTheGrand** [DexxKnight1/TechRevolution#4] opened 2024-01-10 02:27 UTC
### General Info

- [X] I didn't added any mods
- [X] I get this issue consistently in single-player
- [X] I get this issue consistently in multi-player
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.1.1

### Describe your issue

Warp dust from Waystones is currently uncraftable. This is a necessary item in order to complete multiple quests.
Ender pearl in the recipe is replaced with a barrier block named "Empty Tag: forge:ender_pearl"

### Steps to reproduce the issue

1. Open JEI to Warp Dust
2. Left click or press R to view recipe
3. see unobtainable item as part of recipe

### Additional Information

![image](https://github.com/DexxKnight1/TechRevolution/assets/156151416/1188df47-8003-41ab-b28a-ad9a77dc2297)

**Comment by DexxKnight1** [comment] 2024-01-12 12:39
The issue is fixed in v1.1.2

**Closed as completed** 2024-01-12 12:39 UTC
Labels: bug, fixed, High Priority
